version: '3'
services:
  dns-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '53:53/udp'
    volumes:
      - /home/victor/Desktop/retele/proiect-retele-2023-aokay/src/dns_add_blocker:/app 
    restart: always

  ad-blocker-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - dns-server
    restart: always
